import { get } from "@vercel/blob";
import { classifyPdf, extractPagesMarkdown } from "@firecrawl/pdf-inspector";
import { eq } from "drizzle-orm";
import { extractCandidateProfile, evaluateCandidate } from "@/ai/generate";
import { getDb } from "@/db";
import { applications, interviews, jobs } from "@/db/schema";
import { weightedRecommendation } from "@/lib/jobs";

async function loadApplication(applicationId: string) { "use step"; console.info("evaluation:load", { applicationId }); const [row] = await getDb().select({ application: applications, job: jobs }).from(applications).innerJoin(jobs, eq(applications.jobId, jobs.id)).where(eq(applications.id, applicationId)).limit(1); if (!row?.job.rubric) throw new Error("The job rubric is not approved"); return row; }
async function extractResume(applicationId: string, resumeUrl: string) { "use step"; console.info("evaluation:extract", { applicationId }); await getDb().update(applications).set({ status: "extracting" }).where(eq(applications.id, applicationId)); const result = await get(resumeUrl, { access: "private" }); if (!result || result.statusCode !== 200) throw new Error("Resume could not be read from private storage"); const bytes = Buffer.from(await new Response(result.stream).arrayBuffer()); const classification = classifyPdf(bytes); const pages = extractPagesMarkdown(bytes); const text = pages.pages.map((page) => page.markdown).filter(Boolean).join("\n\n"); if (text.trim().length < 80) throw new Error(`Resume is ${classification.pdfType} and requires OCR. Please upload a text-searchable PDF.`); await getDb().update(applications).set({ extractionText: text, extractionType: classification.pdfType, extractionConfidence: classification.confidence }).where(eq(applications.id, applicationId)); return { text, type: classification.pdfType, confidence: classification.confidence };
}
async function profileAndEvaluate(applicationId: string, resumeText: string, rubric: NonNullable<typeof jobs.$inferSelect.rubric>, confidence: number) { "use step"; console.info("evaluation:ai", { applicationId }); await getDb().update(applications).set({ status: "evaluating" }).where(eq(applications.id, applicationId)); const profile = await extractCandidateProfile(resumeText); const evaluation = await evaluateCandidate(profile, rubric); const recommendation = weightedRecommendation(evaluation, rubric, confidence); await getDb().update(applications).set({ profile, evaluation, weightedScore: recommendation.score, recommendation: recommendation.recommendation, needsHumanReview: recommendation.needsHumanReview, status: "review", evaluatedAt: new Date() }).where(eq(applications.id, applicationId)); return recommendation;
}
async function createSchedulingInvitation(applicationId: string, name: string, email: string) { "use step"; console.info("evaluation:scheduling", { applicationId }); const bookingUrl = new URL("https://cal.com/pritish/15min"); bookingUrl.searchParams.set("name", name); bookingUrl.searchParams.set("email", email); bookingUrl.searchParams.set("notes", `Hireflow first interview · application ${applicationId}`); await getDb().insert(interviews).values({ applicationId, bookingUrl: bookingUrl.toString(), status: "invited" }).onConflictDoNothing(); await getDb().update(applications).set({ status: "interview_invited" }).where(eq(applications.id, applicationId)); return bookingUrl.toString(); }
async function markFailed(applicationId: string, message: string) { "use step"; console.error("evaluation:failed", { applicationId, message }); await getDb().update(applications).set({ status: "failed", failureReason: message }).where(eq(applications.id, applicationId)); }
export async function evaluateApplicationWorkflow(applicationId: string) { "use workflow"; console.info("evaluation:start", { applicationId }); try { const row = await loadApplication(applicationId); const extraction = await extractResume(applicationId, row.application.resumeUrl); const result = await profileAndEvaluate(applicationId, extraction.text, row.job.rubric!, extraction.confidence); let bookingUrl: string | null = null; if (result.recommendation === "strong_fit" && !result.needsHumanReview) bookingUrl = await createSchedulingInvitation(applicationId, row.application.candidateName, row.application.candidateEmail); return { ...result, bookingUrl }; } catch (error) { const message = error instanceof Error ? error.message : "Evaluation failed"; await markFailed(applicationId, message); return { failed: true, error: message }; } }
