import { boolean, integer, jsonb, pgEnum, pgTable, real, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import type { CandidateProfile, Evaluation, JobSpec, Rubric } from "@/ai/schemas";
export const jobStatus = pgEnum("job_status", ["draft", "review", "approved", "published", "closed"]);
export const applicationStatus = pgEnum("application_status", ["submitted", "extracting", "evaluating", "review", "interview_invited", "interview_scheduled", "rejected", "failed"]);
export const jobs = pgTable("jobs", { id: uuid("id").defaultRandom().primaryKey(), slug: text("slug").notNull().unique(), title: text("title").notNull(), status: jobStatus("status").notNull().default("draft"), sourcePrompt: text("source_prompt").notNull(), jobSpec: jsonb("job_spec").$type<JobSpec>().notNull(), renderedHtml: text("rendered_html").notNull(), rubric: jsonb("rubric").$type<Rubric>(), rubricVersion: integer("rubric_version").notNull().default(0), createdBy: text("created_by").notNull(), aiModel: text("ai_model"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(), publishedAt: timestamp("published_at", { withTimezone: true }) });
export const jobPostings = pgTable("job_postings", { id: uuid("id").defaultRandom().primaryKey(), jobId: uuid("job_id").notNull().references(() => jobs.id, { onDelete: "cascade" }), provider: text("provider").notNull(), status: text("status").notNull(), externalId: text("external_id"), externalUrl: text("external_url"), demo: boolean("demo").notNull().default(false), error: text("error"), publishedAt: timestamp("published_at", { withTimezone: true }) }, (table) => [uniqueIndex("job_provider_unique").on(table.jobId, table.provider)]);
export const applications = pgTable("applications", { id: uuid("id").defaultRandom().primaryKey(), jobId: uuid("job_id").notNull().references(() => jobs.id, { onDelete: "cascade" }), candidateName: text("candidate_name").notNull(), candidateEmail: text("candidate_email").notNull(), linkedinUrl: text("linkedin_url"), consent: boolean("consent").notNull(), resumeUrl: text("resume_url").notNull(), resumeName: text("resume_name").notNull(), resumeSha256: text("resume_sha256").notNull(), status: applicationStatus("status").notNull().default("submitted"), publicToken: uuid("public_token").defaultRandom().notNull().unique(), extractionText: text("extraction_text"), extractionType: text("extraction_type"), extractionConfidence: real("extraction_confidence"), profile: jsonb("profile").$type<CandidateProfile>(), evaluation: jsonb("evaluation").$type<Evaluation>(), weightedScore: real("weighted_score"), recommendation: text("recommendation"), needsHumanReview: boolean("needs_human_review"), workflowRunId: text("workflow_run_id"), failureReason: text("failure_reason"), submittedAt: timestamp("submitted_at", { withTimezone: true }).defaultNow().notNull(), evaluatedAt: timestamp("evaluated_at", { withTimezone: true }) });
export const interviews = pgTable("interviews", { id: uuid("id").defaultRandom().primaryKey(), applicationId: uuid("application_id").notNull().references(() => applications.id, { onDelete: "cascade" }).unique(), provider: text("provider").notNull().default("cal.com"), bookingUid: text("booking_uid"), bookingUrl: text("booking_url"), startAt: timestamp("start_at", { withTimezone: true }), endAt: timestamp("end_at", { withTimezone: true }), meetingUrl: text("meeting_url"), status: text("status").notNull().default("invited"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const auditEvents = pgTable("audit_events", { id: uuid("id").defaultRandom().primaryKey(), entityType: text("entity_type").notNull(), entityId: uuid("entity_id").notNull(), action: text("action").notNull(), actor: text("actor").notNull(), metadata: jsonb("metadata").$type<Record<string, unknown>>(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
